version: "2"

linters:
  default: none
  enable:
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - unused
    - staticcheck
    - unconvert
    - gocritic
    - durationcheck
  exclusions:
    paths:
      - api/operations
    presets:
      - comments
  settings:
    misspell:
      locale: US
    goheader:
      values:
        regexp:
          copyright-holder: Copyright \(c\) (20\d\d\-20\d\d)|2021|({{year}})
      template-path: .license.tmpl
    revive:
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: var-declaration
        - name: errorf
        # Explicitly disable comment-related rules
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true

formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt
